### PR TITLE
Fixes #2

### LINKED ISSUE #2: PrimSkirt Rezzer - Error - Line 414
LSL-Scripts/PrimSkirt Builder/PrimSkirt Builder/Pose Stand Base/Pose Stand Script.lsl

"(413,28): Error CSO136: A local variable named 'i' cannot be declared in this scope because it would give a different meaning to 'i', which is already used in a 'parent or current' scope to denote something else."

I'm not too familiar with scripting, so not sure how to correct this myself. 

Also, notecard called "Intro" should be changed to "Introduction" or line #222 of the script edited to match.

### PR DESCRIPTION
**Pull request by svandragt**
Fixes #2

### CODE REVIEW

**Comment by Outworldz** [comment]
Thanks for the fix!

**Comment by Araminta** [comment]
Wow! Thanks for fixing this. Much appreciated.

**Comment by Araminta** [comment]
If someone has time to test this, I'd appreciate it. I'm no longer getting a script error, but it's still not functioning. Only one prim is rezzed. Perhaps it's just me?

screen shot 2016-04-18 at 12 08 28 pm

**Comment by Outworldz** [comment]
The dress panel is also upside down

**Comment by Araminta** [comment]
I just tested this in SL and it works (prior to the integer i changes). So must be something with me? Unless it just won't work in OS.

Edit: I exported the working object from SL and imported to OS (Metropolis), and now I get the integer error (which I didn't get in SL). My workaround for now will be to generate any needed skirts in SL and import to OS.  If anyone cares to figure this out, please do let me know! :)

Edit2: Tested on OS Grid, same result. Script returns integer i errors. Removing integer i references allows the script to run, but rezzes one prim as in picture. Oh, and the menu (more less, etc) doesn't seem to function. FYI Wish I knew scripting so I could assist with resolution. :(

**Pull request merged**
